# Generated by Django 5.2 on 2025-05-08 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('kpi_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kpi_name', models.CharField(max_length=50)),
                ('kpi_token', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalambaKPI',
            fields=[
                ('kpi_id', models.AutoField(primary_key=True, serialize=False)),
                ('calamba_kpi', models.CharField(max_length=255)),
                ('kpi_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calamba_kpis', to='kpi_web_app.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='KPIMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kpi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_kpis', to='kpi_web_app.calambakpi')),
            ],
        ),
        migrations.CreateModel(
            name='KPIQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kpi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_kpis', to='kpi_web_app.calambakpi')),
            ],
        ),
        migrations.CreateModel(
            name='KPIWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kpi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_kpis', to='kpi_web_app.calambakpi')),
            ],
        ),
    ]
